// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJzgQpioyF5pK2VVbKUWVEVOCD_6VsiZ0',
    appId: '1:208299809785:web:67ce6b5125125ea44bfb28',
    messagingSenderId: '208299809785',
    projectId: 'mystore-52565',
    authDomain: 'mystore-52565.firebaseapp.com',
    storageBucket: 'mystore-52565.appspot.com',
    measurementId: 'G-T8QRFWCZZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy01Z8Mt9OqiNs9f1FxJIZmJsm95QZH-Y',
    appId: '1:208299809785:android:6d73d08799cf3cd34bfb28',
    messagingSenderId: '208299809785',
    projectId: 'mystore-52565',
    storageBucket: 'mystore-52565.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSpsh26rdtw6vVsuWdejCGfj1DSPi6dgQ',
    appId: '1:208299809785:ios:095d4a27acf9b6da4bfb28',
    messagingSenderId: '208299809785',
    projectId: 'mystore-52565',
    storageBucket: 'mystore-52565.appspot.com',
    iosBundleId: 'com.example.mystore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSpsh26rdtw6vVsuWdejCGfj1DSPi6dgQ',
    appId: '1:208299809785:ios:095d4a27acf9b6da4bfb28',
    messagingSenderId: '208299809785',
    projectId: 'mystore-52565',
    storageBucket: 'mystore-52565.appspot.com',
    iosBundleId: 'com.example.mystore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJzgQpioyF5pK2VVbKUWVEVOCD_6VsiZ0',
    appId: '1:208299809785:web:57da27ce71596ca74bfb28',
    messagingSenderId: '208299809785',
    projectId: 'mystore-52565',
    authDomain: 'mystore-52565.firebaseapp.com',
    storageBucket: 'mystore-52565.appspot.com',
    measurementId: 'G-XRHN6R7JTQ',
  );
}
